/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Board */

#ifndef _Included_Board
#define _Included_Board
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Board
 * Method:    getBoard
 * Signature: ()[[I
 */
JNIEXPORT jobjectArray JNICALL Java_Board_getBoard
  (JNIEnv *, jobject);

/*
 * Class:     Board
 * Method:    updateBoard
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_Board_updateBoard
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     Board
 * Method:    setBoard
 * Signature: ([[I)V
 */
JNIEXPORT void JNICALL Java_Board_setBoard
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     Board
 * Method:    setTour
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_Board_setTour
  (JNIEnv *, jobject, jint);

/*
 * Class:     Board
 * Method:    getNumberOfRedPieces
 * Signature: ()I
 */


#ifdef __cplusplus
}
#endif
#endif
